name: Docker Image CI

on:
  push:
    branches: ["localhost"]
  pull_request:
    branches: ["localhost"]
    types: [closed]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests=true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_USERNAME }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: nxthongbk/stms-user-service:latest

  # Deploy:
  #   if: |
  #     (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true) ||
  #     (github.event_name == 'push' && github.ref == 'refs/heads/develop')
  #   needs: Build
  #   name: Deploy to Server
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Build & Deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USERNAME }}
  #         password: ${{ secrets.SERVER_PASSWORD }}
  #         script: |
  #           cd /home/iot/scity && sudo docker-compose pull user && sudo docker-compose up -d user
